#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AnimalAdjectives.Resource", IsApplication=true)]

namespace AnimalAdjectives
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040002
			public const int background_color = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int main_color = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int main_color_darker = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int second_color = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int title_bar_color = 2130968579;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050001
			public const int main_image_margin_bottom = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int main_image_margin_bottom2 = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int main_image_width = 2131034112;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int facebookshare = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_favorite2 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_action_favorite_selected2 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_action_next_item = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_action_previous_item = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_action_settings = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_launcher = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int icon_sharefb = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080004
			public const int fullWordText = 2131230724;
			
			// aapt resource value: 0x7f080000
			public const int linearLayout1 = 2131230720;
			
			// aapt resource value: 0x7f080003
			public const int linearLayout2 = 2131230723;
			
			// aapt resource value: 0x7f080008
			public const int linearLayout3 = 2131230728;
			
			// aapt resource value: 0x7f080001
			public const int linearLayout4 = 2131230721;
			
			// aapt resource value: 0x7f080009
			public const int nextButton = 2131230729;
			
			// aapt resource value: 0x7f080007
			public const int pictureView = 2131230727;
			
			// aapt resource value: 0x7f080002
			public const int prevButton = 2131230722;
			
			// aapt resource value: 0x7f080006
			public const int spinner = 2131230726;
			
			// aapt resource value: 0x7f080005
			public const int spinnerWrapper = 2131230725;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int ActionBarTheme = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int AppTheme = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int title_style = 2131165186;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
